# Generated by Django 6.0 on 2025-12-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_city_city_name_en_city_city_name_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username_en',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username_ky',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username_ru',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
