# Generated by Django 6.0 on 2025-12-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0004_property_area_property_district_property_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ky',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
