# Generated by Django 6.0 on 2025-12-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0005_alter_city_city_name_alter_city_city_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_image',
        ),
    ]
