# Generated by Django 6.0 on 2025-12-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0006_remove_city_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
