# Generated by Django 6.0 on 2025-12-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0007_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='condition_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='condition_ky',
        ),
        migrations.RemoveField(
            model_name='property',
            name='condition_ru',
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ky',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
