# Generated by Django 6.0 on 2025-12-26 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0008_remove_property_condition_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='property',
        ),
        migrations.AddField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='house_app.property'),
        ),
    ]
